### ISSUE TITLE
select from camera

### ISSUE THREAD

**Issue by ravi9376** [roiperlman/ngx-document-scanner#2]
Hey can i use with camera this plugin direct crop and upload?
if yes then how (in ionic)

**Comment by roiperlman** [comment]
yes, you should configure the input field to open the camera input when clicked.

**Comment by ravi9376** [comment]
hey can i remove the central edit button diff type of filter i need only original?

**Comment by roiperlman** [comment]
it's not possible in the current version, planned for future versions.
